import * as Blockly from 'blockly/core';

const HUE = 120;

Blockly.common.defineBlocksWithJsonArray([
  {
    type: 'python_if',
    message0: 'if %1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'If the condition is true, run the enclosed blocks.',
    helpUrl: '',
  },
  {
    type: 'python_if_else',
    message0: 'if %1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    message2: 'else %1',
    args2: [{ type: 'input_statement', name: 'ELSE' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Run one set of blocks if the condition is true, otherwise run the other set.',
    helpUrl: '',
  },
  {
    type: 'python_repeat',
    message0: 'repeat %1 times',
    args0: [{ type: 'input_value', name: 'TIMES', check: 'Number' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Run the enclosed blocks a fixed number of times.',
    helpUrl: '',
  },
  {
    type: 'python_while',
    message0: 'while %1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Keep running the enclosed blocks while the condition is true.',
    helpUrl: '',
  },
  {
    type: 'python_wait',
    message0: 'wait %1 seconds',
    args0: [{ type: 'input_value', name: 'SECONDS', check: 'Number' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Pause the program for a number of seconds. Useful for animations.',
    helpUrl: '',
  },
]);
