import * as Blockly from 'blockly/core';

const HUE = 120;

Blockly.common.defineBlocksWithJsonArray([
  {
    type: 'python_if',
    message0: 'if %1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'If the condition is true, run the enclosed blocks.',
    helpUrl: '',
  },
  {
    type: 'python_if_else',
    message0: 'if %1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    message2: 'else %1',
    args2: [{ type: 'input_statement', name: 'ELSE' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Run one set of blocks if the condition is true, otherwise run the other set.',
    helpUrl: '',
  },
  {
    type: 'python_repeat',
    message0: 'repeat %1 times',
    args0: [{ type: 'input_value', name: 'TIMES', check: 'Number' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Run the enclosed blocks a fixed number of times.',
    helpUrl: '',
  },
  {
    type: 'python_while',
    message0: 'while %1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Keep running the enclosed blocks while the condition is true.',
    helpUrl: '',
  },
  {
    type: 'python_wait',
    message0: 'wait %1 seconds',
    args0: [{ type: 'input_value', name: 'SECONDS', check: 'Number' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Pause the program for a number of seconds. Useful for animations.',
    helpUrl: '',
  },
  {
    type: 'python_repeat_until',
    message0: 'repeat until %1',
    args0: [{ type: 'input_value', name: 'CONDITION', check: 'Boolean' }],
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Keep running the enclosed blocks until the condition becomes true.',
    helpUrl: '',
  },
  {
    type: 'python_count_with',
    message0: 'count with %1 from %2 to %3',
    args0: [
      { type: 'field_variable', name: 'VAR', variable: 'i' },
      { type: 'input_value', name: 'FROM', check: 'Number' },
      { type: 'input_value', name: 'TO', check: 'Number' },
    ],
    inputsInline: true,
    message1: '%1',
    args1: [{ type: 'input_statement', name: 'DO' }],
    previousStatement: null,
    nextStatement: null,
    colour: HUE,
    tooltip: 'Count from the first number to the second (both included), running the blocks each time.',
    helpUrl: '',
  },
  {
    type: 'python_break',
    message0: 'break out of loop',
    previousStatement: null,
    colour: HUE,
    tooltip: 'Stop the loop this block is inside immediately.',
    helpUrl: '',
  },
  {
    type: 'python_continue',
    message0: 'skip to next loop turn',
    previousStatement: null,
    colour: HUE,
    tooltip: 'Skip the rest of this loop turn and start the next one.',
    helpUrl: '',
  },
]);
